---
- name: Using apt uninstall nodejs
  become: yes
  ansible.builtin.apt:
    name: nodejs
    state: absent

- name: Install the gpg key for nodejs LTS
  become: yes
  apt_key:
    url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
    state: present

- name: Install the nodejs LTS repos
  become: yes
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{ NODEJS_VERSION }}.x {{ ansible_distribution_release }} main"
    state: present
    update_cache: yes

- name: Install the nodejs
  become: yes
  apt:
    name: nodejs
    state: present
    update_cache: yes
